name: Frontend CI

on:
  push:
    branches:
      - main
      - ui
      - 'feature/ui/**'
      - 'fix/ui/**'
  pull_request:
    branches:
      - main
      - ui

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      # Placeholder for tests - will be added in a future step
      # - name: Test
      #   run: pnpm test

      - name: Build
        run: pnpm build
