name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e ".[dev]"
      - run: ruff check . --exit-zero
      - run: mypy --ignore-missing-imports
      - run: pytest -q
  
  e2e:
    runs-on: ubuntu-latest
    services:
      supabase:
        image: supabase/postgres:14.1.0.89
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres -h localhost -p 5432"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Wait for PostgreSQL to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client netcat-openbsd
          for i in {1..15}; do
            pg_isready -U postgres -d postgres -h localhost -p 5432 && echo "PostgreSQL is ready" && break
            echo "Waiting for PostgreSQL... Attempt $i/15"
            sleep 5
            if [ $i -eq 15 ]; then
              echo "PostgreSQL failed to start after multiple attempts" && exit 1
            fi
          done
      - name: Create fixtures directory
        run: mkdir -p cypress/fixtures
      - name: Create sample image for testing
        run: |
          echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==" | base64 -d > cypress/fixtures/roof.jpg
      - name: Run Cypress tests
        run: pnpm exec cypress run
        env:
          SUPABASE_URL: http://localhost:5432