name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # Add environment variables for testing
    env:
      SUPABASE_URL: "https://example.supabase.co"
      SUPABASE_KEY: "dummy_key_for_testing"
      SUPABASE_ANON_KEY: "dummy_anon_key_for_testing"
      SUPABASE_DB_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Install dependencies explicitly
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e ".[dev]"
      
      # Set PYTHONPATH to include the src directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src" >> $GITHUB_ENV
      
      # Run linting and tests
      - run: ruff check . --exit-zero
      - run: mypy 
      - run: pytest -q