name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e ".[dev]"
      - run: ruff check . --exit-zero
      - run: mypy 
      - run: pytest -q
  
  e2e:
    runs-on: ubuntu-latest
    services:
      supabase:
        image: supabase/postgres:15
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm exec cypress run
        env:
          SUPABASE_URL: http://localhost:5432