name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e ".[dev]"
      - run: ruff check . --exit-zero
      - run: mypy 
      - run: pytest -q
  
  e2e:
    runs-on: ubuntu-latest
    services:
      supabase:
        image: supabase/postgres:14.1.0.89
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Wait for PostgreSQL to be ready
        run: |
          apt-get update && apt-get install -y netcat-openbsd
          for i in {1..10}; do
            nc -zv localhost 5432 && echo "PostgreSQL is ready" && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 3
          done
          echo "PostgreSQL failed to start" && exit 1
      - name: Create fixtures directory
        run: mkdir -p cypress/fixtures
      - name: Create sample image for testing
        run: |
          # Create a simple 1x1 pixel image for testing
          echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==" | base64 -d > cypress/fixtures/roof.jpg
      - name: Run Cypress tests
        run: pnpm exec cypress run
        env:
          SUPABASE_URL: http://localhost:5432